// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYN5imqVIa6uEtkItbubZ5oou6Y-dRCz4',
    appId: '1:415089402562:web:8292d76dac05e77f74115b',
    messagingSenderId: '415089402562',
    projectId: 'final-project-2-ac7ed',
    authDomain: 'final-project-2-ac7ed.firebaseapp.com',
    storageBucket: 'final-project-2-ac7ed.appspot.com',
    measurementId: 'G-QVJC6FVBYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzjMEHvojIMHZ6EA_tfbBg4iGVOsp-bIs',
    appId: '1:415089402562:android:574db6e747db686d74115b',
    messagingSenderId: '415089402562',
    projectId: 'final-project-2-ac7ed',
    storageBucket: 'final-project-2-ac7ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJTv1U5RtH5Yam_umkWQKL70z7E4C4HQU',
    appId: '1:415089402562:ios:3e09f6697dbd713874115b',
    messagingSenderId: '415089402562',
    projectId: 'final-project-2-ac7ed',
    storageBucket: 'final-project-2-ac7ed.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJTv1U5RtH5Yam_umkWQKL70z7E4C4HQU',
    appId: '1:415089402562:ios:bf0f71fcc68b475674115b',
    messagingSenderId: '415089402562',
    projectId: 'final-project-2-ac7ed',
    storageBucket: 'final-project-2-ac7ed.appspot.com',
    iosBundleId: 'com.example.project2.RunnerTests',
  );
}
